name: Firebase Firestore Access

on:
  schedule:
    - cron: '40 3 * * *'
    - cron: '40 6 * * *'
    - cron: '40 9 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make cred json
      run: echo "${{ secrets.FIREBASE_CRED_JSON }}" > ${HOME}/firebase_credentials.json

    - name: Run Python Script
      env:
        FIREBASE_CRED_FNAME: ${HOME}/firebase_credentials.json
      run: |
        python main.py

