name: Firebase Firestore Access

on: [push]

jobs:
  access_firestore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check env
      env:
        FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
      run: |
        echo "FIREBASE_ADMIN_SDK"
        echo $FIREBASE_ADMIN_SDK


    - name: Run FastAPI
      env:
        FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
      run: uvicorn main:app --host 0.0.0.0 --port 8000

